language: java
jdk:
  - oraclejdk14

matrix:
  include:
    - os: linux
      dist: bionic

cache:
  directories:
    - $HOME/texlive
    - $HOME/.texlive
    - $HOME/texmf

sudo: false

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y texlive-base texlive-latex-base texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra

install:
  - echo "Override default Travis install step to avoid unnecessary './gradlew assemble'."

script:
  - ./gradlew build --scan -s
