language: java
jdk:
  - oraclejdk14

matrix:
  include:
    - os: linux
      dist: bionic

cache:
  directories:
    - $HOME/texlive
    - $HOME/.texlive
    - $HOME/texmf

sudo: false

before_install:
  - wget https://raw.githubusercontent.com/y-yu/install-tex-travis/master/install-tex.sh
  - wget https://raw.githubusercontent.com/y-yu/install-tex-travis/master/tlmgr.sh
  - chmod +x install-tex.sh tlmgr.sh

install:
  - . ./install-tex.sh

script:
  - . ./gradlew build --scan -s
